### ISSUE TITLE
Error: Could Not Recognize Post Type

### ISSUE THREAD

**Issue by isaiiah** [JackhammerYT/RedDownloader#37] opened 2023-01-17 01:42 UTC
I have a little automation that has been working for a few months now. But now it is throwing 

"RedDownloader.Download(url=download_url, output=download_name, quality=1080)
Error: Could Not Recoganize Post Type"

Is it just me? Any idea for a fix? download_Url is the correct post url/perma link.

**Comment by JackhammerYT** [comment] 2023-01-17 03:46
Could you give an example for an url that is throwing that issue?

Thanks

**Comment by navid-sheik** [comment] 2023-01-17 23:37
Same, when you try to download a video from Reddit, it says "Error: Could Not Recoganize Post Type". This only happens with video, this is the example I used:
https://www.reddit.com/r/gtaonline/comments/108zrxo/by_sheer_coincidence_i_offer_you_an_external_view/

**Comment by JackhammerYT** [comment] 2023-01-18 16:14
@navid-sheik and @isaiiah Thanks for bringing the issue to my notice there was a bug on RedDownloader Response Server which has been patched now. You should be able to use the package as intended.

All the media are being downloaded after the patch hence i'll be closing this issue however if you may face an issue please don't hesitate to reopen this issue.

Thank You

**Closed by JackhammerYT** 2023-01-18 16:14 UTC
